select * from customer limit 20

--q1.what is the total revenue generated by male or female customers?
select gender,SUM(purchase_amount)  as revenue
from customer 
group by gender

--q2.which customer used a discount bt still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='yes' and purchase_amount >= (select AVG(purchase_amount)from customer)

--q3.which are the top 5 products with highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--q4.compare the average purchase amounts between standard and express shipping.
select shipping_type,
ROUND (AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--q5.do subscribed customers spend more? compare average spend and the total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id)as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--q6.which 5 products have the highest % of purchases with discount applied?
SELECT item_purchased,
       ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--q7.segment customers into new,returning and loyal based on their total number of previous purchases,and

with customer_type as (
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases =1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
	END AS customer_segment
from customer	
)

select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

	
--q8.what are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
COUNT(customer_id)as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3; 
